### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rajathkmp** [bwohlberg/sporco-notebooks#1]
`module 'sporco.plot' has no attribute 'config_notebook_plotting'`

was attempting to run the CDL, any workaround?

**Comment by bwohlberg** [comment]
I suspect that you're trying to use the notebooks with the most recent release of the SPORCO package from ``pip`` instead of with the development version from GitHub. Please try the development version (see the note that I have just added to the README file for sporco-notebooks) to see if that resolves this problem.

**Comment by rajathkmp** [comment]
@bwohlberg  works! thanks
